name: Targets OpenWRT Builder

on:
 workflow_dispatch:

jobs:
 target-build:
  runs-on: Ubuntu-20.04
  container: kerongbaby/openwrt:latest

  steps:
  # Those steps are executed directly on the VM
  # Github workflows set container HOME as '/github/home', so use absolute path
   run: |
    set -ex
    tar -zxf /home/openwrt/openwrt.sources.tgz -C /home/openwrt
    cd /home/openwrt/openwrt
    cp /home/openwrt/devices/at91sama5d3_xplain/.config ./
    make defconfig
    make -j$(nproc) || make V=s
