name: OpenWRT Docker Image for Builder

on:
 workflow_dispatch:

jobs:
 build-openwrt-docker:
  runs-on: Ubuntu-20.04

  steps:
   # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
   - uses: actions/checkout@master

   - name: Set up QEMU
     uses: docker/setup-qemu-action@master
   - name: Set up Docker Buildx
     uses: docker/setup-buildx-action@master
   - name: Login to DockerHub
     uses: docker/login-action@master
     with:
      username: ${{ secrets.DOCKER_ACCOUNT }}
      password: ${{ secrets.DOCKER_PASSWORD }}
   - name: Build and Push OpenWRT tools Docker
     id: openwrt-docker-build
     uses: docker/build-push-action@master
     with:
      push: true
      context: docker/
      file: docker/Dockerfile.arm-toolchain
      tags: kerongbaby/openwrt-toolchain:latest
