name: Targets OpenWRT Builder

on:
 workflow_dispatch:

jobs:
 target-build:
  runs-on: Ubuntu-20.04
  container: kerongbaby/openwrt:latest

  steps:
  # Those steps are executed directly on the VM
  # Github workflows set container HOME as '/github/home', so use absolute path
   - name: untar
     run: |
      set -ex
      tar -zxf /home/openwrt/openwrt.sources.tgz -C /home/openwrt
